### Get All orders
GET  http://localhost:5000/api/v1/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxMDI4MjM0NS1jNDAwLTQ1ZTgtOWE0OS01NjYyY2VlZmMwMTAiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMxODExMDQsImV4cCI6MTcwMzM1MzkwNCwiaWF0IjoxNzAzMTgxMTA0LCJpc3MiOiJWZXJhIENoYW5nIiwiYXVkIjoiRWNvbW1lcmNlIn0.eWMCyJima-uOsGUlaVgwK4izF0JAp1uB4hnuOsoytv0
 

### get an order by id
GET http://localhost:5000/api/v1/orders/7e12c54d-f215-4835-a8c6-10fcd573de85
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxMDI4MjM0NS1jNDAwLTQ1ZTgtOWE0OS01NjYyY2VlZmMwMTAiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMxNjgzMjksImV4cCI6MTcwMzM0MTEyOSwiaWF0IjoxNzAzMTY4MzI5LCJpc3MiOiJWZXJhIENoYW5nIiwiYXVkIjoiRWNvbW1lcmNlIn0.hxiJWjUf_kKr8O7tSyZs_PI2bemyYITULTTwtwrhLK8


### create an order "UserId": "03e5da24-f6dc-414c-a24f-cbc1d8baafb2",
POST  http://localhost:5000/api/v1/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJmZWIwZWNjOS1mMDc0LTRlYTMtYjQ2My1mZDM1MzA2MmQ1YjQiLCJyb2xlIjoiQ3VzdG9tZXIiLCJuYmYiOjE3MDMyNzExNTIsImV4cCI6MTcwMzQ0Mzk1MiwiaWF0IjoxNzAzMjcxMTUyLCJpc3MiOiJWZXJhIENoYW5nIiwiYXVkIjoiRWNvbW1lcmNlIn0.07c5L904x3-jjQb17GVg_N8ihGrXZEf0rPTSX4Xvqvc


{
    "PurchaseItemCreateDTOs":[
        {
            "ProductId": "bc7083bd-a02c-4162-8d0c-8f484a14d503",
            "Quantity": 1
        }
    ]
}


### update an order
PUT http://localhost:5000/api/v1/orders/7e12c54d-f215-4835-a8c6-10fcd573de85
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxMDI4MjM0NS1jNDAwLTQ1ZTgtOWE0OS01NjYyY2VlZmMwMTAiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMxODExMDQsImV4cCI6MTcwMzM1MzkwNCwiaWF0IjoxNzAzMTgxMTA0LCJpc3MiOiJWZXJhIENoYW5nIiwiYXVkIjoiRWNvbW1lcmNlIn0.eWMCyJima-uOsGUlaVgwK4izF0JAp1uB4hnuOsoytv0

{
    "Status":"Delivered"
}



### cancel an order
DELETE  http://localhost:5000/api/v1/orders/b20d7960-ca27-4a4a-b852-90ffea327baf
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJlMTIwNjRjZC0xNTM2LTQ3NzItOGY2MC1hNDdhNTVjMjYzMmYiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3MDMwMDYxNjAsImV4cCI6MTcwMzE3ODk2MCwiaWF0IjoxNzAzMDA2MTYwLCJpc3MiOiJWZXJhIENoYW5nIiwiYXVkIjoiRWNvbW1lcmNlIn0.NDSx4C8PLTiCIJzVxitk4enTxR-L801N1CijGUcm08A
