### Get All Categories
GET http://localhost:5000/api/v1/categories
Content-Type: application/json


### get a single category by id
GET http://localhost:5000/api/v1/categories/d746fc29-ea09-4688-818b-63d6bb6822fc
Content-Type: application/json


### create a new category
POST  http://localhost:5000/api/v1/categories
Content-Type: application/json


{
    "Name":"Plant Seeds",
    "Image":"https://fakeimg.pl/200x200"
}


### update a category
PUT http://localhost:5000/api/v1/categories/e374607e-7c01-46d1-81a6-94b9ac43ddc2
Content-Type: application/json

{
    "Name":"Interior Decoration",
    "Image":"https://fakeimg.pl/200x200"
}



### update a category
DELETE  http://localhost:5000/api/v1/categories/bc55e7f9-4f3c-4105-a439-a8a61b46f734
